name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: restore gradle.properties
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          MONKE_DB_URL: ${{ secrets.MONKE_DB_URL }}
          MONKE_DB_USER: ${{ secrets.MONKE_DB_USER }}
          MONKE_DB_PASSWORD: ${{ secrets.MONKE_DB_PASSWORD }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: gradlew build
        run: |
          ./gradlew clean build -x jooq
      - name: docker build
        run: |
          docker build . -t toadlesss/monkebot:latest
      - name: docker push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: toadlesss/monkebot
          tags: latest
      - name: reload vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd ~/docker/monkebot
            ./rebuild.sh